--INSERT INTO STUDENT (NAME, ROLLNO, AGE) VALUES ('alex', 101, 23);
--INSERT INTO STUDENT (NAME, ROLLNO, AGE) VALUES ('max', 102, 23);
--INSERT INTO STUDENT (NAME, ROLLNO, AGE) VALUES ('jerry', 103, 23);
--
--INSERT INTO COURSE (COURSE_ID, NAME) VALUES (1, 'math');
--INSERT INTO COURSE (COURSE_ID, NAME) VALUES (2, 'english');
--INSERT INTO COURSE (COURSE_ID, NAME) VALUES (3, 'art');

DELETE FROM STUDENT WHERE STUDENT_ID = 3;